openapi: 3.0.0
servers:
  - url: 'https://slack.com/api/'
info:
  description: >-
    This is OpenAPI specification for Slack API.
  version: 0.0.1
  title: OpenAPI specification for Slack API
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Slack
    description: Slack messaging platform
paths:
  /api.test:
    post:
      tags:
        - Test
      summary: Checks API calling code.
      description: 'Tier 4: This method helps you test your calling code.'
      operationId: apiTest
      parameters:
        - name: error
          in: query
          description: Error response to return
          required: false
          schema:
            type: string
        - name: foo
          in: query
          description: Example property to return
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiTestResponse'
      requestBody:
        $ref: '#/components/requestBodies/EmptyBody'

externalDocs:
  description: Find out more about Slack API
  url: 'https://api.slack.com/'
components:
  requestBodies:
    EmptyBody:
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schema/EmptyBody'
        application/json:
          schema:
            $ref: '#/components/schema/EmptyBody'
      description: An empty object
      required: false
  schemas:
    ApiTestResponse:
      title:
      description:
      type: object
      required:
        - ok
      properties:
        ok:
          type: boolean
        error:
          type: string
        args:
          $ref: '#/components/schema/ApiTestArgsResponse'
    ApiTestArgsResponse:
      title: Response object for api.test endpoint
      description:
      type: object
      properties:
        error:
          type: string
        foo:
          type: string
    EmptyBody:
      title: Empty request body object
      description: Empty request body object
      type: object